/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as DiligenceRouteImport } from './routes/diligence'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as PersonasRouteImport } from './routes/personas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const DiligenceRoute = DiligenceRouteImport.update({
  id: '/diligence',
  path: '/diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/diligence': typeof DiligenceRoute
  '/finance': typeof FinanceRoute
  '/leads': typeof LeadsRoute
  '/personas': typeof PersonasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/diligence': typeof DiligenceRoute
  '/finance': typeof FinanceRoute
  '/leads': typeof LeadsRoute
  '/personas': typeof PersonasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/diligence': typeof DiligenceRoute
  '/finance': typeof FinanceRoute
  '/leads': typeof LeadsRoute
  '/personas': typeof PersonasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ads' | '/diligence' | '/finance' | '/leads' | '/personas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ads' | '/diligence' | '/finance' | '/leads' | '/personas'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/diligence'
    | '/finance'
    | '/leads'
    | '/personas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  DiligenceRoute: typeof DiligenceRoute
  FinanceRoute: typeof FinanceRoute
  LeadsRoute: typeof LeadsRoute
  PersonasRoute: typeof PersonasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diligence': {
      id: '/diligence'
      path: '/diligence'
      fullPath: '/diligence'
      preLoaderRoute: typeof DiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  DiligenceRoute: DiligenceRoute,
  FinanceRoute: FinanceRoute,
  LeadsRoute: LeadsRoute,
  PersonasRoute: PersonasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
